android_config: &android_config
  docker:
    - image: circleci/android:api-25-alpha
  environment:
    TERM: dumb
    GRADLE_OPTS: '-Dorg.gradle.daemon=false'

gradle_key: &gradle_key
  jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "api/build.gradle" }}-{{ checksum "app/build.gradle" }}

restore_gradle_cache: &restore_gradle_cache
  restore_cache:
    key: *gradle_key

save_gradle_cache: &save_gradle_cache
  save_cache:
    key: *gradle_key
    paths:
      - ~/.gradle
      - ~/.m2

android_dependencies: &android_dependencies
  run:
    name: Download Android Dependencies
    command: ./gradlew androidDependencies

version: 2
jobs:
  test:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *android_dependencies
      - *save_gradle_cache
      - run:
          name: Run Tests with coverage
          command: ./gradlew jacocoTestReport
      - store_artifacts:
          path: api/build/reports
          destination: reports
      - store_test_results:
          path: api/build/test-results
  upload:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *android_dependencies
      - *save_gradle_cache
      - run:
          name: Upload artifacts to Bintray
          command: ./gradlew install bintrayUpload

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - upload:
          requires:
            - test
          filters:
            branches:
              only: master